### PR TITLE
Issue-253 Configure cache so EhCache is used instead of the default cache

### LINKED ISSUE #253: Cache configuration not set up properly
Issue Description
--
[Description of the issue, with example/screenshot. Description of what the desired behavior should be. Should be complete before Review is approved]

While FUSE has the `ehcache.xml` configuration included, it is not set up correctly. Because a `CacheManager` bean is not created in the `AppConfig`, Spring uses a default simple cache provider which stores values in an instance of `ConcurrentHashMap`. This Stackoverflow [answer ](https://stackoverflow.com/questions/41739581/default-cache-manager-with-spring-boot-using-enablecaching) provides more details on the default cache manager. Right now, the FUSE cache will fill up forever and its entries will never expire with the `ConcurrentHashMap`.

*Example 1:*
I added the following to `SettlementRestController`
```
  @Autowired
  org.springframework.cache.CacheManager springCacheManager;

  private void cacheStats(String id) {
    System.out.println(id);

    CacheManager cacheManager = CacheManager.getInstance();
    Cache cache = cacheManager.getCache("missions");

    System.out.println("---EhCache Info---");
    System.out.println("Cache: " + cache);
    System.out.println("Size: " + cache.getSize());
    System.out.println("Hit Count: " + cache.getStatistics().cacheHitCount());
    System.out.println("Miss Count: " + cache.getStatistics().cacheMissCount());

    System.out.println("---Spring Cache Info---");
    org.springframework.cache.Cache springCache = springCacheManager.getCache("missions");
    System.out.println("Spring cache class: " + springCache.getClass());
    ConcurrentHashMap springCacheHashMap = (ConcurrentHashMap) springCache.getNativeCache();
    System.out.println("Size: " + springCacheHashMap.size());
    System.out.println();
  }
```
And I changed the getMission method to print the cache stats:
```
    +cacheStats("BEFORE");
    // if an external request id was provided, grab it
    processRequestId(requestId);

    Optional<SettlementMission> msn = getMissionInternal(id);

    +cacheStats("AFTER");
    if (msn.isPresent()) {
      return settlementMissionTranslator.translate(msn.get());
    }

    throw new EntityNotFoundException(SettlementMission.class, id.toString());
```
I then called the following to create a new settlement and get it.
```
POST localhost:8080/settlementEngine
{
	"agreements": [{
		"id": 4,
		"instrument": "test3",
		"internalParty": "test",
		"externalParty": "test",
		"buySell": "B",
		"qty": 1
	}]
}

GET localhost:8080/settlementEngine/mission/1
```
This prints out these statements:
```
BEFORE
---EhCache Info---
Cache: [ name = missions status = STATUS_ALIVE eternal = false overflowToDisk = false maxEntriesLocalHeap = 16384 maxEntriesLocalDisk = 0 memoryStoreEvictionPolicy = LRU timeToLiveSeconds = 1200 timeToIdleSeconds = 0 persistence = none diskExpiryThreadIntervalSeconds = 120 cacheEventListeners: ; orderedCacheEventListeners:  maxBytesLocalHeap = 0 overflowToOffHeap = false maxBytesLocalOffHeap = 0 maxBytesLocalDisk = 0 pinned = false ]
Size: 0
Hit Count: 0
Miss Count: 0
---Spring Cache Info---
Spring cache class: class org.springframework.cache.concurrent.ConcurrentMapCache
Size: 0

AFTER
---EhCache Info---
Cache: [ name = missions status = STATUS_ALIVE eternal = false overflowToDisk = false maxEntriesLocalHeap = 16384 maxEntriesLocalDisk = 0 memoryStoreEvictionPolicy = LRU timeToLiveSeconds = 1200 timeToIdleSeconds = 0 persistence = none diskExpiryThreadIntervalSeconds = 120 cacheEventListeners: ; orderedCacheEventListeners:  maxBytesLocalHeap = 0 overflowToOffHeap = false maxBytesLocalOffHeap = 0 maxBytesLocalDisk = 0 pinned = false ]
Size: 0
Hit Count: 0
Miss Count: 0
---Spring Cache Info---
Spring cache class: class org.springframework.cache.concurrent.ConcurrentMapCache
Size: 1
```

The Spring cache is the `ConcurrentHashMap` instead of EhCache and that increases in size while the ehcache does not get anything added to it.

*Example 2:*
To confirm that the ehcache configuration did not currently affect the cache, I changed the `timeToLiveSeconds` to 1, and I added a test method to delete settlement missions from the repository using DELETE.
```
POST localhost:8080/settlementEngine
{
	"agreements": [{
		"id": 4,
		"instrument": "test3",
		"internalParty": "test",
		"externalParty": "test",
		"buySell": "B",
		"qty": 1
	}]
}

GET localhost:8080/settlementEngine/mission/1
DELETE localhost:8080/settlementEngine/mission/1
>Wait several seconds
GET localhost:8080/settlementEngine/mission/1
```

This produces the following logs. Despite the cache config evicting cache keys after 1 second, the GET statement returns the same settlement mission after several seconds even though it was deleted. This is because the `ConcurrentHashMap` has no configuration and does not delete any keys.
```
ADD MISSION
2019.01.04 10:20:44.002 [qtp1864344016-22] INFO  o.g.s.e.SettlementRestController - 1861990405 - ↓settleAgreement(TradeAgreementMessages(agreements=[TradeAgreementMessage(id=4, instrument=test3, internalParty=test, externalParty=test, buySell=B, qty=1.0)]), null)
2019.01.04 10:20:44.182 [qtp1864344016-22] INFO  o.g.s.s.SettlementService - 1861990405 - Returning 1 mission id(s)
2019.01.04 10:20:44.215 [qtp1864344016-22] INFO  o.g.s.e.SettlementRestController - 1861990405 - ↑settleAgreement(TradeAgreementMessages(agreements=[TradeAgreementMessage(id=4, instrument=test3, internalParty=test, externalParty=test, buySell=B, qty=1.0)]), null) → SettlementResponseMessage(spawnedMissions=[/settlementEngine/mission/1])
2019.01.04 10:20:44.255 [qtp1864344016-22] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 1861990405 - Attempting to add audit headers
2019.01.04 10:20:44.264 [qtp1864344016-22] INFO  o.g.s.u.FuseTraceRepository - 1861990405 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=POST, path=/settlementEngine, headers={request={Origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=de9713c2-6f46-4d5d-bced-86440e05283a, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9, Content-Length=144, Content-Type=application/json}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 15:20:43 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"spawnedMissions":["/settlementEngine/mission/1"]}, request-payload={
	"agreements": [{
		"id": 4,
		"instrument": "test3",
		"internalParty": "test",
		"externalParty": "test",
		"buySell": "B",
		"qty": 1
	}]
}}, Tracer={internal-request-id=1861990405, trace-end-UTC=2019-01-04T15:20:44.263Z, trace-timing-ms=346, trace-start-UTC=2019-01-04T15:20:43.917Z}}
GET MISSION
2019.01.04 10:20:47.234 [qtp1864344016-19] INFO  o.g.s.e.SettlementRestController - 261798826 - ↓getMission(1, null)
2019.01.04 10:20:47.256 [qtp1864344016-19] INFO  o.g.s.e.SettlementRestController - 261798826 - ↑getMission(1, null) → SettlementMissionMessage(id=1, instrument=test3, externalParty=test, depot=DTC, direction=REC, qty=1.0)
2019.01.04 10:20:47.269 [qtp1864344016-19] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 261798826 - Attempting to add audit headers
2019.01.04 10:20:47.270 [qtp1864344016-19] INFO  o.g.s.u.FuseTraceRepository - 261798826 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=GET, path=/settlementEngine/mission/1, headers={request={Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=623462c4-e6cc-5d23-1f5f-46aa5fbe76f2, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 15:20:47 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"id":1,"instrument":"test3","externalParty":"test","depot":"DTC","direction":"REC","qty":1.0}, request-payload=}, Tracer={internal-request-id=261798826, trace-end-UTC=2019-01-04T15:20:47.270Z, trace-timing-ms=43, trace-start-UTC=2019-01-04T15:20:47.228Z}}
DELETE MISSION
2019.01.04 10:20:50.079 [qtp1864344016-23] INFO  o.g.s.e.SettlementRestController - 175672766 - ↓deleteMission(1, null)
2019.01.04 10:20:50.093 [qtp1864344016-23] INFO  o.g.s.e.SettlementRestController - 175672766 - ↑deleteMission(1, null)
2019.01.04 10:20:50.095 [qtp1864344016-23] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 175672766 - Attempting to add audit headers
2019.01.04 10:20:50.095 [qtp1864344016-23] INFO  o.g.s.u.FuseTraceRepository - 175672766 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=DELETE, path=/settlementEngine/mission/1, headers={request={Origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=ab855648-44d6-f78f-4823-e8bc513f1211, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 15:20:50 GMT, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload=, request-payload=}, Tracer={internal-request-id=175672766, trace-end-UTC=2019-01-04T15:20:50.095Z, trace-timing-ms=19, trace-start-UTC=2019-01-04T15:20:50.076Z}}
GET MISSION
2019.01.04 10:20:57.687 [qtp1864344016-20] INFO  o.g.s.e.SettlementRestController - 1834104937 - ↓getMission(1, null)
2019.01.04 10:20:57.688 [qtp1864344016-20] INFO  o.g.s.e.SettlementRestController - 1834104937 - ↑getMission(1, null) → SettlementMissionMessage(id=1, instrument=test3, externalParty=test, depot=DTC, direction=REC, qty=1.0)
2019.01.04 10:20:57.689 [qtp1864344016-20] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 1834104937 - Attempting to add audit headers
2019.01.04 10:20:57.690 [qtp1864344016-20] INFO  o.g.s.u.FuseTraceRepository - 1834104937 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=GET, path=/settlementEngine/mission/1, headers={request={Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=d798f05d-e563-b05b-2a49-5d00fb1f4f5e, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 15:20:57 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"id":1,"instrument":"test3","externalParty":"test","depot":"DTC","direction":"REC","qty":1.0}, request-payload=}, Tracer={internal-request-id=1834104937, trace-end-UTC=2019-01-04T15:20:57.690Z, trace-timing-ms=6, trace-start-UTC=2019-01-04T15:20:57.684Z}}
```

We want to switch over to actually using the ehcache implementation. The instructions [here ](https://www.mkyong.com/spring/spring-caching-and-ehcache-example/) show a standard approach to using ehcache with Spring.

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

The description of the root cause is included in the Issue Description above. To fix this issue, I will follow the instructions [here](https://www.mkyong.com/spring/spring-caching-and-ehcache-example/).

This requires `spring-context` and `spring-context-support` to be added as dependencies to the `pom.xml`. The `AppConfig` also requires a `CacheManager` based on `EhCacheCacheManager` to be created. I will specify `ehcache.xml` in the `application.yml` as `cache-config` and pass this into `AppConfig` with `@Value` annotation.

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

No documentation changes are needed. This is a bug fix.

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

I repeated the tests that I included in the Issue Description.

*Example 1:*
```
BEFORE
---EhCache Info---
Cache: [ name = missions status = STATUS_ALIVE eternal = false overflowToDisk = false maxEntriesLocalHeap = 16384 maxEntriesLocalDisk = 0 memoryStoreEvictionPolicy = LRU timeToLiveSeconds = 1200 timeToIdleSeconds = 0 persistence = none diskExpiryThreadIntervalSeconds = 120 cacheEventListeners: ; orderedCacheEventListeners:  maxBytesLocalHeap = 0 overflowToOffHeap = false maxBytesLocalOffHeap = 0 maxBytesLocalDisk = 0 pinned = false ]
Size: 0
Hit Count: 0
Miss Count: 0
---Spring Cache Info---
Spring cache class: class org.springframework.cache.ehcache.EhCacheCache
Size: 0

AFTER
---EhCache Info---
Cache: [ name = missions status = STATUS_ALIVE eternal = false overflowToDisk = false maxEntriesLocalHeap = 16384 maxEntriesLocalDisk = 0 memoryStoreEvictionPolicy = LRU timeToLiveSeconds = 1200 timeToIdleSeconds = 0 persistence = none diskExpiryThreadIntervalSeconds = 120 cacheEventListeners: ; orderedCacheEventListeners:  maxBytesLocalHeap = 0 overflowToOffHeap = false maxBytesLocalOffHeap = 0 maxBytesLocalDisk = 0 pinned = false ]
Size: 1
Hit Count: 0
Miss Count: 2
---Spring Cache Info---
Spring cache class: class org.springframework.cache.ehcache.EhCacheCache
Size: 1
```

The Spring cache and the EhCache are now the same cache.

*Example 2:*

```
CREATE MISSION
2019.01.04 11:04:14.183 [qtp1391249801-21] INFO  o.g.s.e.SettlementRestController - 2129762332 - ↓settleAgreement(TradeAgreementMessages(agreements=[TradeAgreementMessage(id=4, instrument=test3, internalParty=test, externalParty=test, buySell=B, qty=1.0)]), null)
2019.01.04 11:04:14.351 [qtp1391249801-21] INFO  o.g.s.s.SettlementService - 2129762332 - Returning 1 mission id(s)
2019.01.04 11:04:14.386 [qtp1391249801-21] INFO  o.g.s.e.SettlementRestController - 2129762332 - ↑settleAgreement(TradeAgreementMessages(agreements=[TradeAgreementMessage(id=4, instrument=test3, internalParty=test, externalParty=test, buySell=B, qty=1.0)]), null) → SettlementResponseMessage(spawnedMissions=[/settlementEngine/mission/1])
2019.01.04 11:04:14.428 [qtp1391249801-21] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 2129762332 - Attempting to add audit headers
2019.01.04 11:04:14.437 [qtp1391249801-21] INFO  o.g.s.u.FuseTraceRepository - 2129762332 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=POST, path=/settlementEngine, headers={request={Origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=50945e7b-9623-9a0a-6524-75d139862e95, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9, Content-Length=144, Content-Type=application/json}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:04:14 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"spawnedMissions":["/settlementEngine/mission/1"]}, request-payload={
	"agreements": [{
		"id": 4,
		"instrument": "test3",
		"internalParty": "test",
		"externalParty": "test",
		"buySell": "B",
		"qty": 1
	}]
}}, Tracer={internal-request-id=2129762332, trace-end-UTC=2019-01-04T16:04:14.436Z, trace-timing-ms=324, trace-start-UTC=2019-01-04T16:04:14.112Z}}
GET MISSION
2019.01.04 11:04:15.510 [qtp1391249801-19] INFO  o.g.s.e.SettlementRestController - 995856742 - ↓getMission(1, null)
2019.01.04 11:04:15.540 [qtp1391249801-19] INFO  o.g.s.e.SettlementRestController - 995856742 - ↑getMission(1, null) → SettlementMissionMessage(id=1, instrument=test3, externalParty=test, depot=DTC, direction=REC, qty=1.0)
2019.01.04 11:04:15.552 [qtp1391249801-19] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 995856742 - Attempting to add audit headers
2019.01.04 11:04:15.552 [qtp1391249801-19] INFO  o.g.s.u.FuseTraceRepository - 995856742 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=GET, path=/settlementEngine/mission/1, headers={request={Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=7c2e8132-a466-9379-549d-73acd469f92a, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:04:15 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"id":1,"instrument":"test3","externalParty":"test","depot":"DTC","direction":"REC","qty":1.0}, request-payload=}, Tracer={internal-request-id=995856742, trace-end-UTC=2019-01-04T16:04:15.552Z, trace-timing-ms=47, trace-start-UTC=2019-01-04T16:04:15.505Z}}
DELETE MISSION
2019.01.04 11:04:18.427 [qtp1391249801-20] INFO  o.g.s.e.SettlementRestController - 1560046734 - ↓deleteMission(1, null)
2019.01.04 11:04:18.445 [qtp1391249801-20] INFO  o.g.s.e.SettlementRestController - 1560046734 - ↑deleteMission(1, null)
2019.01.04 11:04:18.446 [qtp1391249801-20] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 1560046734 - Attempting to add audit headers
2019.01.04 11:04:18.446 [qtp1391249801-20] INFO  o.g.s.u.FuseTraceRepository - 1560046734 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=DELETE, path=/settlementEngine/mission/1, headers={request={Origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=7cde8293-840d-26cd-6c21-bffe0ce31853, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:04:18 GMT, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload=, request-payload=}, Tracer={internal-request-id=1560046734, trace-end-UTC=2019-01-04T16:04:18.446Z, trace-timing-ms=22, trace-start-UTC=2019-01-04T16:04:18.424Z}}
GET MISSION
2019.01.04 11:04:26.687 [qtp1391249801-22] INFO  o.g.s.e.SettlementRestController - 1290537618 - ↓getMission(1, null)
2019.01.04 11:04:26.689 [qtp1391249801-22] ERROR o.g.s.e.SettlementRestController - 1290537618 - ⇑getMission(1, null) ⇒ org.galatea.starter.entrypoint.exception.EntityNotFoundException: Entity 1 of type SettlementMission was not found
org.galatea.starter.entrypoint.exception.EntityNotFoundException: Entity 1 of type SettlementMission was not found
2019.01.04 11:04:26.701 [qtp1391249801-22] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 1290537618 - Attempting to add audit headers
2019.01.04 11:04:26.702 [qtp1391249801-22] INFO  o.g.s.u.FuseTraceRepository - 1290537618 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=GET, path=/settlementEngine/mission/1, headers={request={Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=59688952-c97b-381a-8333-7ec8b56f20bf, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:04:26 GMT, Content-Type=application/json;charset=utf-8, status=404}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"status":"NOT_FOUND","message":"org.galatea.starter.entrypoint.exception.EntityNotFoundException: Entity 1 of type SettlementMission was not found"}, request-payload=}, Tracer={internal-request-id=1290537618, trace-end-UTC=2019-01-04T16:04:26.702Z, trace-timing-ms=19, trace-start-UTC=2019-01-04T16:04:26.683Z}}
```

The cache now expires immediately as expected when the `timeToLiveSeconds` is changed to 1.

*Example 3:*

As an additional test, if we changed the `timeToLiveSeconds` back to 1200, the GET request is cached and returns the mission even after it is deleted as expected of the cache.

```
CREATE MISSION
2019.01.04 11:11:50.935 [qtp1391249801-20] INFO  o.g.s.e.SettlementRestController - 738901044 - ↓settleAgreement(TradeAgreementMessages(agreements=[TradeAgreementMessage(id=4, instrument=test3, internalParty=test, externalParty=test, buySell=B, qty=1.0)]), null)
2019.01.04 11:11:51.085 [qtp1391249801-20] INFO  o.g.s.s.SettlementService - 738901044 - Returning 1 mission id(s)
2019.01.04 11:11:51.118 [qtp1391249801-20] INFO  o.g.s.e.SettlementRestController - 738901044 - ↑settleAgreement(TradeAgreementMessages(agreements=[TradeAgreementMessage(id=4, instrument=test3, internalParty=test, externalParty=test, buySell=B, qty=1.0)]), null) → SettlementResponseMessage(spawnedMissions=[/settlementEngine/mission/1])
2019.01.04 11:11:51.156 [qtp1391249801-20] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 738901044 - Attempting to add audit headers
2019.01.04 11:11:51.164 [qtp1391249801-20] INFO  o.g.s.u.FuseTraceRepository - 738901044 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=POST, path=/settlementEngine, headers={request={Origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=b15d7077-5ab2-c0de-cf60-3c6614eb600d, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9, Content-Length=144, Content-Type=application/json}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:11:50 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"spawnedMissions":["/settlementEngine/mission/1"]}, request-payload={
	"agreements": [{
		"id": 4,
		"instrument": "test3",
		"internalParty": "test",
		"externalParty": "test",
		"buySell": "B",
		"qty": 1
	}]
}}, Tracer={internal-request-id=738901044, trace-end-UTC=2019-01-04T16:11:51.163Z, trace-timing-ms=304, trace-start-UTC=2019-01-04T16:11:50.860Z}}
GET MISSION
2019.01.04 11:11:52.587 [qtp1391249801-19] INFO  o.g.s.e.SettlementRestController - 865192204 - ↓getMission(1, null)
2019.01.04 11:11:52.615 [qtp1391249801-19] INFO  o.g.s.e.SettlementRestController - 865192204 - ↑getMission(1, null) → SettlementMissionMessage(id=1, instrument=test3, externalParty=test, depot=DTC, direction=REC, qty=1.0)
2019.01.04 11:11:52.628 [qtp1391249801-19] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 865192204 - Attempting to add audit headers
2019.01.04 11:11:52.629 [qtp1391249801-19] INFO  o.g.s.u.FuseTraceRepository - 865192204 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=GET, path=/settlementEngine/mission/1, headers={request={Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=044638d6-bab4-a2bf-1482-a514bd02a6f0, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:11:52 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"id":1,"instrument":"test3","externalParty":"test","depot":"DTC","direction":"REC","qty":1.0}, request-payload=}, Tracer={internal-request-id=865192204, trace-end-UTC=2019-01-04T16:11:52.629Z, trace-timing-ms=47, trace-start-UTC=2019-01-04T16:11:52.582Z}}
DELETE MISSION
2019.01.04 11:11:54.014 [qtp1391249801-22] INFO  o.g.s.e.SettlementRestController - 1955316826 - ↓deleteMission(1, null)
2019.01.04 11:11:54.033 [qtp1391249801-22] INFO  o.g.s.e.SettlementRestController - 1955316826 - ↑deleteMission(1, null)
2019.01.04 11:11:54.034 [qtp1391249801-22] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 1955316826 - Attempting to add audit headers
2019.01.04 11:11:54.034 [qtp1391249801-22] INFO  o.g.s.u.FuseTraceRepository - 1955316826 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=DELETE, path=/settlementEngine/mission/1, headers={request={Origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=ae872180-c9f5-f208-ff7a-f343ec13ff7c, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:11:54 GMT, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload=, request-payload=}, Tracer={internal-request-id=1955316826, trace-end-UTC=2019-01-04T16:11:54.034Z, trace-timing-ms=23, trace-start-UTC=2019-01-04T16:11:54.011Z}}
GET MISSION
2019.01.04 11:11:57.224 [qtp1391249801-23] INFO  o.g.s.e.SettlementRestController - 423164266 - ↓getMission(1, null)
2019.01.04 11:11:57.224 [qtp1391249801-23] INFO  o.g.s.e.SettlementRestController - 423164266 - ↑getMission(1, null) → SettlementMissionMessage(id=1, instrument=test3, externalParty=test, depot=DTC, direction=REC, qty=1.0)
2019.01.04 11:11:57.225 [qtp1391249801-23] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 423164266 - Attempting to add audit headers
2019.01.04 11:11:57.226 [qtp1391249801-23] INFO  o.g.s.u.FuseTraceRepository - 423164266 - Adding trace info: {FuseWebRequestTraceFilter={spring-trace={method=GET, path=/settlementEngine/mission/1, headers={request={Cache-Control=no-cache, Accept=*/*, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, Host=localhost:8080, Postman-Token=ee49bc82-831e-7a1c-d15a-c0c3966cdb6e, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Fri, 04 Jan 2019 16:11:57 GMT, Content-Type=application/json;charset=utf-8, status=200}}, contextPath=, parameters={}, remoteAddress=0:0:0:0:0:0:0:1}, request-success=true, response-payload={"id":1,"instrument":"test3","externalParty":"test","depot":"DTC","direction":"REC","qty":1.0}, request-payload=}, Tracer={internal-request-id=423164266, trace-end-UTC=2019-01-04T16:11:57.226Z, trace-timing-ms=5, trace-start-UTC=2019-01-04T16:11:57.221Z}}
```

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

### PR DESCRIPTION
**Pull request by wmvsilva**
See #253.

The cache was not set up correctly and was using the default simple Spring implementation instead of the config in `ehcache.xml`. This PR fixes this so the `ehcache.xml` config is used.

### CODE REVIEW

File: src/main/java/org/galatea/starter/AppConfig.java [hunk 1]
```diff
@@ -4,17 +4,25 @@
...
+import org.springframework.core.io.ClassPathResource;
 
 @Slf4j
 @Configuration
 @EnableAspectJAutoProxy
 @EnableCaching
 public class AppConfig {
 
+  @Value("${cache-config}")
+  public String cacheConfig;
```
Comment (GalateaEric) [inline src/main/java/org/galatea/starter/AppConfig.java]: can we move this to not be a member variable, and instead do an @Value on a method parameter to the @Bean ehCacheCacheManager() method

**Review by GalateaEric — COMMENTED** [review]
Can we create some unit tests that demonstrate the EhCache usage -- some what as you described in the test evidence of the issue.  To guard against someone accidentally disabling EhCache with a change in the future.

File: src/main/java/org/galatea/starter/AppConfig.java (hunk 1 above)
Comment (wmvsilva) [reply src/main/java/org/galatea/starter/AppConfig.java]: Fixed

**Comment by wmvsilva** [comment]
I've made changes based on @GalateaEric's comments. I've added a Unit Test to confirm that EhCache can be properly created/configured from an ehcache.xml config file.

It would be nice to have more extensive testing that the Cache is actually caching missions for the settlements endpoint. However, it looks like that would involve expanding the tests to run a full version of the app. While we already have integration tests, those actually connect to https://fuse-rest-dev.cfapps.io to perform the tests. In order to test specific behavior of a cache that we can easily configure, I think that a full instance of the app with an H2 database should be brought up as part of the normal tests. I've done this in other API projects before where the `application.yml` is fully populated for tests and connects to a local database that we populate before test queries are run.

File: src/main/java/org/galatea/starter/AppConfig.java [hunk 2]
```diff
@@ -38,6 +43,29 @@ public IAgreementTransformer agreementTransformer() {
...
+    return new EhCacheCacheManager(ehCacheCacheManager.getObject());
+  }
+
+  /**
+   * Creates factory bean for cache manager using a cache config file.
+   *
+   * @return factory bean for the EhCache to be passed to EhCacheCacheManager.
+   */
+  @Bean
+  public EhCacheManagerFactoryBean ehCacheCacheManager(
```
Comment (cbaltera) [inline src/main/java/org/galatea/starter/AppConfig.java]: Can we change the name of this bean so that it's clear that it isn't itself the cache manager? (and also its use as param in the bean above)

Comment (wmvsilva) [reply src/main/java/org/galatea/starter/AppConfig.java]: I've updated the name of the bean and the parameter in the bean above.

**Review by cbaltera — APPROVED** [review]
